// <auto-generated />
// Hand-authored snapshot paired with migration <c>20260926120000_InitialSchema</c>.
// Regenerate with <c>dotnet ef migrations add</c> once the project has been
// built and the baseline migration applied against a fresh SQLite database.

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using PersonalCrm.Infrastructure.Persistence;

#nullable disable

namespace PersonalCrm.Infrastructure.Persistence.Migrations.SqliteMigrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("PersonalCrm.Core.Domain.Attachment", b =>
            {
                b.Property<string>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("ContactId")
                    .HasColumnType("TEXT");

                b.Property<string>("ContentType")
                    .HasMaxLength(255)
                    .HasColumnType("TEXT");

                b.Property<string>("CreatedAt")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Filename")
                    .IsRequired()
                    .HasMaxLength(512)
                    .HasColumnType("TEXT");

                b.Property<string>("InteractionId")
                    .HasColumnType("TEXT");

                b.Property<long>("SizeBytes")
                    .HasColumnType("INTEGER");

                b.Property<string>("Sha256")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT");

                b.Property<string>("StorageKey")
                    .IsRequired()
                    .HasMaxLength(1024)
                    .HasColumnType("TEXT");

                b.Property<string>("WorkspaceId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("ContactId");

                b.HasIndex("InteractionId");

                b.HasIndex("StorageKey");

                b.HasIndex(new[] { "WorkspaceId", "CreatedAt" }, "ix_attachments_workspace_created_at");

                b.HasOne("PersonalCrm.Core.Domain.Contact", "Contact")
                    .WithMany()
                    .HasForeignKey("ContactId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.HasOne("PersonalCrm.Core.Domain.Interaction", "Interaction")
                    .WithMany("Attachments")
                    .HasForeignKey("InteractionId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.ToTable("attachments", (string)null);
            });

            modelBuilder.Entity("PersonalCrm.Core.Domain.AuditLog", b =>
            {
                b.Property<string>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<int>("Action")
                    .HasColumnType("INTEGER");

                b.Property<string>("ActorDisplayName")
                    .IsRequired()
                    .HasMaxLength(120)
                    .HasColumnType("TEXT");

                b.Property<string>("ActorUserId")
                    .HasColumnType("TEXT");

                b.Property<string>("EntityId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT");

                b.Property<string>("EntityType")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT");

                b.Property<string>("IpAddress")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT");

                b.Property<string>("OccurredAt")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Payload")
                    .HasColumnType("text");

                b.Property<string>("WorkspaceId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex(new[] { "EntityType", "EntityId" }, "ix_audit_logs_entity");

                b.HasIndex(new[] { "WorkspaceId", "OccurredAt" }, "ix_audit_logs_workspace_occurred_at");

                b.ToTable("audit_logs", (string)null);
            });

            modelBuilder.Entity("PersonalCrm.Core.Domain.Circle", b =>
            {
                b.Property<string>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("Color")
                    .HasMaxLength(16)
                    .HasColumnType("TEXT");

                b.Property<string>("CreatedAt")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(60)
                    .HasColumnType("TEXT");

                b.Property<string>("WorkspaceId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex(new[] { "WorkspaceId", "Name" }, "ux_circles_workspace_name")
                    .IsUnique();

                b.HasOne("PersonalCrm.Core.Domain.Workspace", "Workspace")
                    .WithMany("Circles")
                    .HasForeignKey("WorkspaceId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.ToTable("circles", (string)null);
            });

            modelBuilder.Entity("PersonalCrm.Core.Domain.Contact", b =>
            {
                b.Property<string>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("Anniversary")
                    .HasColumnType("TEXT");

                b.Property<string>("Birthday")
                    .HasColumnType("TEXT");

                b.Property<int?>("CadenceDays")
                    .HasColumnType("INTEGER");

                b.Property<string>("CreatedAt")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("DeletedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasMaxLength(120)
                    .HasColumnType("TEXT");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasMaxLength(120)
                    .HasColumnType("TEXT");

                b.Property<string>("MiddleName")
                    .HasMaxLength(120)
                    .HasColumnType("TEXT");

                b.Property<string>("PhotoUrl")
                    .HasMaxLength(2048)
                    .HasColumnType("TEXT");

                b.Property<string>("Pronouns")
                    .HasMaxLength(40)
                    .HasColumnType("TEXT");

                b.Property<string>("UpdatedAt")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("Version")
                    .IsConcurrencyToken()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("INTEGER")
                    .HasDefaultValue(0);

                b.Property<string>("WorkspaceId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("DeletedAt");

                b.HasIndex(new[] { "WorkspaceId", "LastName", "FirstName" }, "ix_contacts_workspace_name");

                b.HasOne("PersonalCrm.Core.Domain.Workspace", "Workspace")
                    .WithMany("Contacts")
                    .HasForeignKey("WorkspaceId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.ToTable("contacts", (string)null);
            });

            modelBuilder.Entity("PersonalCrm.Core.Domain.ContactCircle", b =>
            {
                b.Property<string>("ContactId")
                    .HasColumnType("TEXT");

                b.Property<string>("CircleId")
                    .HasColumnType("TEXT");

                b.Property<string>("AddedAt")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey(new[] { "ContactId", "CircleId" });

                b.HasOne("PersonalCrm.Core.Domain.Circle", "Circle")
                    .WithMany("Members")
                    .HasForeignKey("CircleId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.HasOne("PersonalCrm.Core.Domain.Contact", "Contact")
                    .WithMany("Circles")
                    .HasForeignKey("ContactId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.ToTable("contact_circles", (string)null);
            });

            modelBuilder.Entity("PersonalCrm.Core.Domain.ContactMethod", b =>
            {
                b.Property<string>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("ContactId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<bool>("IsPrimary")
                    .ValueGeneratedOnAdd()
                    .HasDefaultValue(false)
                    .HasColumnType("INTEGER");

                b.Property<int>("Kind")
                    .HasColumnType("INTEGER");

                b.Property<string>("Label")
                    .HasMaxLength(40)
                    .HasColumnType("TEXT");

                b.Property<string>("Value")
                    .IsRequired()
                    .HasMaxLength(2048)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex(new[] { "ContactId", "Kind", "IsPrimary" }, "ix_contact_methods_contact_kind_primary");

                b.HasIndex("Value");

                b.HasOne("PersonalCrm.Core.Domain.Contact", "Contact")
                    .WithMany("Methods")
                    .HasForeignKey("ContactId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.ToTable("contact_methods", (string)null);
            });

            modelBuilder.Entity("PersonalCrm.Core.Domain.ContactTag", b =>
            {
                b.Property<string>("ContactId")
                    .HasColumnType("TEXT");

                b.Property<string>("TagId")
                    .HasColumnType("TEXT");

                b.Property<string>("AddedAt")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey(new[] { "ContactId", "TagId" });

                b.HasOne("PersonalCrm.Core.Domain.Contact", "Contact")
                    .WithMany("Tags")
                    .HasForeignKey("ContactId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.HasOne("PersonalCrm.Core.Domain.Tag", "Tag")
                    .WithMany("Contacts")
                    .HasForeignKey("TagId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.ToTable("contact_tags", (string)null);
            });

            modelBuilder.Entity("PersonalCrm.Core.Domain.Interaction", b =>
            {
                b.Property<string>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<Guid>("ClientGeneratedId")
                    .HasColumnType("TEXT");

                b.Property<string>("CreatedAt")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("Direction")
                    .HasColumnType("INTEGER");

                b.Property<int?>("DurationMinutes")
                    .HasColumnType("INTEGER");

                b.Property<int>("Kind")
                    .HasColumnType("INTEGER");

                b.Property<string>("Location")
                    .HasMaxLength(255)
                    .HasColumnType("TEXT");

                b.Property<string>("OccurredAt")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Summary")
                    .HasMaxLength(4096)
                    .HasColumnType("TEXT");

                b.Property<string>("UpdatedAt")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("Version")
                    .IsConcurrencyToken()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("INTEGER")
                    .HasDefaultValue(0);

                b.Property<string>("WorkspaceId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("ClientGeneratedId")
                    .IsUnique()
                    .HasDatabaseName("ux_interactions_client_generated_id");

                b.HasIndex(new[] { "WorkspaceId", "OccurredAt" }, "ix_interactions_workspace_occurred_at");

                b.HasOne("PersonalCrm.Core.Domain.Workspace", "Workspace")
                    .WithMany()
                    .HasForeignKey("WorkspaceId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.ToTable("interactions", (string)null);
            });

            modelBuilder.Entity("PersonalCrm.Core.Domain.InteractionContact", b =>
            {
                b.Property<string>("InteractionId")
                    .HasColumnType("TEXT");

                b.Property<string>("ContactId")
                    .HasColumnType("TEXT");

                b.HasKey(new[] { "InteractionId", "ContactId" });

                b.HasIndex("ContactId");

                b.HasOne("PersonalCrm.Core.Domain.Contact", "Contact")
                    .WithMany("Interactions")
                    .HasForeignKey("ContactId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.HasOne("PersonalCrm.Core.Domain.Interaction", "Interaction")
                    .WithMany("Participants")
                    .HasForeignKey("InteractionId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.ToTable("interaction_contacts", (string)null);
            });

            modelBuilder.Entity("PersonalCrm.Core.Domain.Note", b =>
            {
                b.Property<string>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("ContactId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("ContentMarkdown")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("CreatedAt")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("UpdatedAt")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("Version")
                    .IsConcurrencyToken()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("INTEGER")
                    .HasDefaultValue(0);

                b.Property<string>("WorkspaceId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex(new[] { "ContactId", "UpdatedAt" }, "ix_notes_contact_updated_at");

                b.HasOne("PersonalCrm.Core.Domain.Contact", "Contact")
                    .WithMany("Notes")
                    .HasForeignKey("ContactId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.HasOne("PersonalCrm.Core.Domain.Workspace", "Workspace")
                    .WithMany()
                    .HasForeignKey("WorkspaceId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.ToTable("notes", (string)null);
            });

            modelBuilder.Entity("PersonalCrm.Core.Domain.Instance", b =>
            {
                b.Property<string>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("CreatedAt")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("DefaultLanguage")
                    .HasMaxLength(16)
                    .HasColumnType("TEXT");

                b.Property<string>("SetupCompletedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("SiteName")
                    .IsRequired()
                    .HasMaxLength(120)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("instances", (string)null);
            });

            modelBuilder.Entity("PersonalCrm.Core.Domain.Interaction", b =>
            {
                b.Property<string>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("ActorUserId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<Guid>("ClientGeneratedId")
                    .HasColumnType("TEXT");

                b.Property<string>("Error")
                    .HasColumnType("TEXT");

                b.Property<string>("OperationType")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT");

                b.Property<string>("PayloadJson")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("ReceivedAt")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("Status")
                    .HasColumnType("INTEGER");

                b.Property<string>("WorkspaceId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("AppliedAt")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("ClientGeneratedId")
                    .IsUnique()
                    .HasDatabaseName("ux_outbox_client_generated_id");

                b.HasIndex(new[] { "Status", "ReceivedAt" }, "ix_outbox_status_received_at");

                b.HasIndex(new[] { "WorkspaceId", "ActorUserId" }, "ix_outbox_workspace_actor");

                b.ToTable("outbox_entries", (string)null);
            });

            modelBuilder.Entity("PersonalCrm.Core.Domain.Reminder", b =>
            {
                b.Property<string>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("CompletedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("ContactId")
                    .HasColumnType("TEXT");

                b.Property<string>("CreatedAt")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("DueAt")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("Kind")
                    .HasColumnType("INTEGER");

                b.Property<string>("Notes")
                    .HasMaxLength(4096)
                    .HasColumnType("TEXT");

                b.Property<string>("SnoozedUntil")
                    .HasColumnType("TEXT");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("TEXT");

                b.Property<string>("WorkspaceId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex(new[] { "ContactId", "DueAt" }, "ix_reminders_contact_due_at");

                b.HasIndex(new[] { "WorkspaceId", "DueAt" }, "ix_reminders_workspace_due_at");

                b.HasOne("PersonalCrm.Core.Domain.Contact", "Contact")
                    .WithMany("Reminders")
                    .HasForeignKey("ContactId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.HasOne("PersonalCrm.Core.Domain.Workspace", "Workspace")
                    .WithMany()
                    .HasForeignKey("WorkspaceId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.ToTable("reminders", (string)null);
            });

            modelBuilder.Entity("PersonalCrm.Core.Domain.Tag", b =>
            {
                b.Property<string>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("Color")
                    .HasMaxLength(16)
                    .HasColumnType("TEXT");

                b.Property<string>("CreatedAt")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(60)
                    .HasColumnType("TEXT");

                b.Property<string>("WorkspaceId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex(new[] { "WorkspaceId", "Name" }, "ux_tags_workspace_name")
                    .IsUnique();

                b.HasOne("PersonalCrm.Core.Domain.Workspace", "Workspace")
                    .WithMany("Tags")
                    .HasForeignKey("WorkspaceId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.ToTable("tags", (string)null);
            });

            modelBuilder.Entity("PersonalCrm.Core.Domain.User", b =>
            {
                b.Property<string>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("CreatedAt")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("DisplayName")
                    .IsRequired()
                    .HasMaxLength(120)
                    .HasColumnType("TEXT")
                    .HasDefaultValue("");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(320)
                    .HasColumnType("TEXT");

                b.Property<bool>("IsEmailVerified")
                    .ValueGeneratedOnAdd()
                    .HasDefaultValue(false)
                    .HasColumnType("INTEGER");

                b.Property<bool>("IsInstanceAdmin")
                    .ValueGeneratedOnAdd()
                    .HasDefaultValue(false)
                    .HasColumnType("INTEGER");

                b.Property<string>("LastLoginAt")
                    .HasColumnType("TEXT");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasMaxLength(512)
                    .HasColumnType("TEXT");

                b.Property<string>("PreferredLanguage")
                    .HasMaxLength(16)
                    .HasColumnType("TEXT");

                b.Property<string>("TimeZone")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("Email")
                    .IsUnique()
                    .HasDatabaseName("ux_users_email");

                b.ToTable("users", (string)null);
            });

            modelBuilder.Entity("PersonalCrm.Core.Domain.UserSession", b =>
            {
                b.Property<string>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("CreatedAt")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("ExpiresAt")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("IpAddress")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT");

                b.Property<string>("RefreshTokenHash")
                    .IsRequired()
                    .HasMaxLength(512)
                    .HasColumnType("TEXT");

                b.Property<string>("RevokedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("UserAgent")
                    .HasMaxLength(512)
                    .HasColumnType("TEXT");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("RefreshTokenHash")
                    .IsUnique()
                    .HasDatabaseName("ux_user_sessions_refresh_token_hash");

                b.HasIndex("UserId");

                b.HasOne("PersonalCrm.Core.Domain.User", "User")
                    .WithMany("Sessions")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.ToTable("user_sessions", (string)null);
            });

            modelBuilder.Entity("PersonalCrm.Core.Domain.Workspace", b =>
            {
                b.Property<string>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("CreatedAt")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Icon")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT");

                b.Property<bool>("IsPersonal")
                    .ValueGeneratedOnAdd()
                    .HasDefaultValue(false)
                    .HasColumnType("INTEGER");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(120)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("Name");

                b.ToTable("workspaces", (string)null);
            });

            modelBuilder.Entity("PersonalCrm.Core.Domain.WorkspaceMember", b =>
            {
                b.Property<string>("UserId")
                    .HasColumnType("TEXT");

                b.Property<string>("WorkspaceId")
                    .HasColumnType("TEXT");

                b.Property<string>("JoinedAt")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("Role")
                    .HasColumnType("INTEGER");

                b.HasKey(new[] { "WorkspaceId", "UserId" });

                b.HasIndex("UserId");

                b.HasOne("PersonalCrm.Core.Domain.User", "User")
                    .WithMany("Memberships")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.HasOne("PersonalCrm.Core.Domain.Workspace", "Workspace")
                    .WithMany("Members")
                    .HasForeignKey("WorkspaceId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.ToTable("workspace_members", (string)null);
            });

#pragma warning restore 612, 618
        }
    }
}
