namespace PersonalCrm.Core.Domain;

/// <summary>
/// Server-side mirror of writes that originated offline on a WASM client.
/// When a PWA client creates an interaction while offline it queues the
/// write into IndexedDB; once online the request reaches the server with
/// the same client-generated id, which is recorded here so the Outbox
/// Reconciler can confirm durable storage and free the client queue.
/// </summary>
public class OutboxEntry
{
    public Guid Id { get; set; }

    public Guid WorkspaceId { get; set; }

    public Guid ActorUserId { get; set; }

    /// <summary>UUIDv7 generated by the client; the idempotency key.</summary>
    public Guid ClientGeneratedId { get; set; }

    public string OperationType { get; set; } = string.Empty;

    public string PayloadJson { get; set; } = string.Empty;

    public OutboxStatus Status { get; set; }

    public DateTimeOffset ReceivedAt { get; set; }

    public DateTimeOffset? AppliedAt { get; set; }

    public string? Error { get; set; }
}

public enum OutboxStatus
{
    Pending  = 0,
    Applied  = 1,
    Conflict = 2,
    Rejected = 3
}
